version: '3.8'
services:
  web:
    build: .
    ports:
      - "9090:80"
    volumes:
      - ./src:/var/www/html
    command: ["apache2ctl", "-D", "FOREGROUND"]
    links:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: college_portal
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
